config_version = 13

[audio]
enable_overdrive = true

[bar]
order = [ "default" ]

    [bar.default]
    center = [ "media", "active_window" ]
    end = [
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "control-center",
        "wallpaper",
        "session"
    ]
    font_family = "Ubuntu Sans"
    margin_edge = 0
    margin_ends = 0
    radius = 0
    shadow = false
    start = [ "launcher", "workspaces", "taskbar", "clock", "date", "caffeine", "keyboard_layout" ]
    thickness = 27

[desktop_widgets]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
corner_radius_scale = 1.3500000201165676
font_family = "Ubuntu Sans"
launch_apps_as_systemd_services = true
show_location = false

    [shell.panel]
    launcher_placement = "attached"
    launcher_session_search = true

[theme]
custom_palette = "GruvboxMain"
source = "custom"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper.automation]
order = "alphabetical"

[wallpaper.default]
path = "/home/nix/Pictures/Wallpapers/wallhaven-8gkdy2.jpg"


[wallpaper.monitors.eDP-1]
path = "/home/nix/Pictures/Wallpapers/wallhaven-8gkdy2.jpg"


[widget.media]
hide_when_no_media = true

[widget.taskbar]
group_by_workspace = true
group_single_icon_per_app = true
hide_empty_workspaces = true
only_active_workspace = true
show_workspace_label = false
workspace_group_capsule = false

[widget.workspaces]
active_pill_size = 1.8
